CREATE DATABASE OnlineStore

CREATE TABLE ItemTypes
(
	ItemTypeID VARCHAR(10) PRIMARY KEY,
	Name VARCHAR(40) NOT NULL
)

CREATE TABLE Items
(
	ItemID INT PRIMARY KEY IDENTITY, 
	Name NVARCHAR(20),
	ItemTypeID VARCHAR(10) FOREIGN KEY REFERENCES ItemTypes(ItemTypeID)
)

CREATE TABLE Cities
(
	CityID INT PRIMARY KEY, 
	Name NVARCHAR(20)
)

CREATE TABLE Customers
(
	CustomerID INT PRIMARY KEY, 
	Name NVARCHAR(40),
	Birthday DATE,
	CityID INT FOREIGN KEY REFERENCES Cities(CityID)
)


CREATE TABLE Orders
(
	OrderID INT PRIMARY KEY, 
	CustomerID INT FOREIGN KEY REFERENCES Customers(CustomerID)
)

CREATE TABLE OrderItems
(
	OrderID INT FOREIGN KEY REFERENCES Orders(OrderID), 
	ItemID INT FOREIGN KEY REFERENCES Items(ItemID),
	PRIMARY KEY(OrderID, ItemID)
)